### ISSUE TITLE
Leetcode SRS

### ISSUE THREAD

**Issue by 100phlecs** [bottleware/ideas#1]
I think finding a way to integrate spaced repetition and leetcode would be a really great idea.

You wouldn't forget how to solve a particular problem. 
You would also hold onto methods to solve new problems.

The brute force path would be to make your own anki deck as you do leetcode, and then reimplement problems when they pop up again. Definitely doesn't require any new code. Just something interesting for you to implement - if one wanted to make their own wanikani, except for leetcode, I suppose.

**Comment by goodecf** [comment]
For sure it could be optimized. I wonder if there is a way, based on problem solutions, we could determine what would be a good next problem based off of the one's you have already solved, i.e. one that's just slightly harder, thus more than just easy-medium-hard classifications.

This can be done with Anki & an addon, but one would need to have a keyword or two for each solution so you could sort by those. E.g. don't show leetcode problem #10 (an anki card) or something unless the user has learned how to sort arrays. This sounds very time consuming to do it for every leetcode problem, although one could do this with just a subset of say 100 leetcode problems. You'd still have to find all of the solutions. Then the problem lies that it would assume each user would solve a problem a certain way.

Regardless, I think there's definitely something into trying to optimize leetcode.

**Comment by 100phlecs** [comment]
> we could determine what would be a good next problem based off of the one's you have already solved

This is the main pain point when I open up leetcode. If there is a recommended path to go down on, that'd be awesome.

As for the leetcode addon, I saw someone added an SRS chrome extension. Could build one for firefox, instead of syncing it to anki. 
But yeah, if there was
1. a clear line of problems to dive into, the most bang for your buck 
2. an easy way to revisit solved problems following SRS guidelines

What I mean by one is the (Pareto Principle)[https://en.wikipedia.org/wiki/Pareto_principle] - solving a problem like this: https://leetcode.com/problems/bitwise-and-of-numbers-range/ (which is a clear gotcha)
isn't comparable to understanding dynamic programming deeply.
